os: Visual Studio 2015

environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Debug

  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Release

  #- GENERATOR: "Visual Studio 14 2015"
  #  CONFIG: Debug

  #- GENERATOR: "Visual Studio 14 2015"
  #  CONFIG: Release

install:
 - git submodule update --init --recursive

build_script:
 - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
 - cmd: set CTEST_OUTPUT_ON_FAILURE=1
 - cmd: cmake --version
 - cmd: mkdir build
 - cmd: cd build
 - cmd: cmake .. -G"%GENERATOR%"
 - cmd: cmake --build . --config %CONFIG%
 - cmd: cmake --build . --config %CONFIG% --target check
