syntax = "proto3";

import "base_types.proto";

package pb_message.game_data;


message nation_and_object_id_t
{
    int32 nation_id = 1;
    int32 object_id = 2;
}

message game_start_params_t
{
    // TODO: scenario
    // TODO: options for development levels?

    float habitable_systems_per_hex_mean = 1; // Must be >= 0.1.
    float habitable_systems_per_hex_plus_minus = 2; // interpreted as 3 sigmas
    int32 systems_per_hex = 3; // total, not habitable
    int32 map_height = 4; // In hexes; must be an odd number >= 11.

    map<int32, int32> player_id_to_nation_id = 5; // size of this is the number of human players
    int32 ai_opponents = 6;
}

enum cargo_kind_t {
    invalid_cargo_kind = 0;
    water = -1;                 // part of the ship design; used by crew
    supplies = -2;
    fuel = -3;
    rounds = -4;
    missiles = -5;
    troops = -6;
    colonists = -7;
    cargo_metal = -8;
    cargo_energy = -9;
    cargo_fuel_minerals = -10;
    cargo_water = -11;          // not part of the ship design; just cargo
    cargo_food = -12;
}

enum hit_table_entry_t {
    invalid_hit_table_entry = 0;
    hit_propulsion = 1;
    hit_weapons = 2;
    hit_shields = 3;
    hit_detection = 4;
    hit_stealth = 5;
    hit_fuel = 6;
    hit_water = 7;
    hit_supplies = 8;
    hit_rounds = 9;
    hit_missiles = 10;
    hit_fighters = 11;
    hit_cargo = 12;     // represents storage/cargo/empty slot; if < 0, look it up in cargo_kind_t
    hit_destroyed = 13;
    hit_unused = 14;
}

message unit_design_t
{
    nation_and_object_id_t id = 1;

    // user design; some values may differ after the design is complete; see below
    int32 hull = 2;
    int32 armor = 3;
    int32 propulsion = 4;
    int32 weapons = 5;
    int32 shields = 6;
    int32 detection = 7;
    int32 stealth = 8;
    int32 fuel = 9;
    int32 water = 10;
    int32 supplies = 11;
    int32 rounds = 12;      // storage units, not individual salvos
    int32 missiles = 13;    // storage units, not individual salvos
    int32 fighters = 14;    // each point is a fighter bay with 1 fighter factor
    int32 cargo = 15;

    // hull space occupied by each; will be >= than ideal; ideal is 10 per level
    int32 propulsion_space = 16;
    int32 weapons_space = 17;
    int32 shields_space = 18;
    int32 detection_space = 19;
    int32 stealth_space = 20;

    // actual level of each equipment in the design; will be <= than ideal; ideal is the level above
    float effective_propulsion = 21;
    float effective_weapons = 22;
    float effective_shields = 23;
    float effective_detection = 24;
    float effective_stealth = 25;

    // each out of 100
    int32 propulsion_reliability = 26;
    int32 weapons_reliability = 27;
    int32 shields_reliability = 28;
    int32 detection_reliability = 29;
    int32 stealth_reliability = 30;

    int32 known_propulsion_failures = 31;
    int32 known_weapons_failures = 32;
    int32 known_shields_failures = 33;
    int32 known_detection_failures = 34;
    int32 known_stealth_failures = 35;

    float design_months_remaining = 36;

    bytes hit_table = 100;

    bool failed_design = 101;
    bool obsolete = 102;
}

message unit_t
{
    nation_and_object_id_t id = 1;
    int32 hull = 2;
    int32 armor = 3;
    float propulsion = 4;
    float weapons = 5;
    float shields = 6;
    float detection = 7;
    float stealth = 8;
    float fuel = 9;
    float water = 10;
    float supplies = 11;
    int32 rounds = 12;       // individual salvos
    int32 missiles = 13;     // individual salvos
    int32 fighters = 14;
    bytes cargo = 15;        // must be kept in sync with hit_table
    int32 organization = 16;
    int32 experience = 17;
    int32 crew = 18;
    bytes hit_table = 19;    // populated during combat as hits are resolved; only kept outside of combat if there is damage
}

message fleet_position_t
{
    // always used
    double world_pos_x = 1;
    double world_pos_y = 2;

    // unused (system_id is a negative value) when between systems
    int32 system_id = 3;
    bool at_permanent_location = 4;
    int32 location_index = 5;
    int32 object_index = 6; // -1 if this fleet is not at a particular object
    bool is_garrison = 7; // only meaningful if object_index != -1, and the associated .planet_id != -1 too
};

message fleet_t
{
    nation_and_object_id_t id = 1; // -1 for both of these indicates this fleet is invalid
    pb_message.mission_t mission = 2;
    repeated unit_t units = 3;
    fleet_position_t position = 4;
    int32 fleet_experience = 5;
}

message fleets_t
{
    map<int32, int32> fleet_ids = 1;
}

message resource_t
{
    int32 availability = 1;      // this settlement
    int32 max_availability = 2;  // the whole planet
    float stockpile = 3;
    float max_stockpile = 4;
    float stockpile_last_month = 5;
}

message settlement_t
{
    nation_and_object_id_t id = 1;
    int32 planet_id = 2;

    int32 original_owner = 3;

    // These two are floats because they grow over time; the effeective
    // property is the truncated integral value though.
    float population = 4;
    float infrastructure = 5;

    resource_t water = 6;
    resource_t food = 7;
    resource_t energy = 8;
    resource_t metal = 9;
    resource_t fuel_minerals = 10;

    int32 shipyard_pops = 11;
    int32 infrastructure_upgrade_pops = 12;
    int32 infrastructure_maintenance_pops = 13;
    int32 infrastructure_repair_pops = 14;

    int32 water_pops = 15;
    int32 food_pops = 16;
    int32 energy_pops = 17;
    int32 metal_pops = 18;
    int32 fuel_minerals_pops = 19;

    int32 fuel_refining_pops = 20;
    int32 supply_manufaturing_pops = 21;
    int32 round_manufaturing_pops = 22;
    int32 missile_manufaturing_pops = 23;
    int32 fighter_manufaturing_pops = 24;

    // TODO: language, culture, religion

    repeated nation_and_object_id_t garrison = 25;
    // TODO: ground-to-space defenses
}

enum planet_type_t {
    invalid_planet_type = 0;
    rocky = 1;
    gas_giant = 2;
    ice_giant = 3;
}

enum atmosphere_type_t {
    invalid_atmosphere_type = 0;
    reduced_type_a = 1;
    oxidized_type_b = 2;
    carbon_rich_type_c = 3;
    high_temperature = 4;
    gas_giant_atmosphere = 5;
    ice_giant_atmosphere = 6;
}

message planet_effect_t
{
    string name = 1;
    string reason = 2;
    float value = 3;
}

message planet_t
{
    int32 system_id = 1;
    planet_type_t planet_type = 2;
    double mass_kg = 3;
    double radius_km = 4;
    float orbit_au = 5;
    float orbital_period_y = 6; // in Earth years
    float gravity_g = 7; // in G's
    float axial_tilt_d = 8;
    float day_h = 9;
    float surface_temperature_k = 10;
    float magnetosphere_strength = 11; // Earth-scaled (1.0 is like Earth)
    float atmospheric_pressure = 12; // In "atmospheres" (1.0 is like Earth)
    float o2_co2_suitability = 13; // only applies when atmosphere_type is oxidized_type_b; Earth-scaled
    float ocean_coverage = 14;
    float growth_factor = 15;
    atmosphere_type_t atmosphere_type = 16;
    int32 water = 17;
    int32 food = 18;
    int32 energy = 19;
    int32 metal = 20;
    int32 fuel_minerals = 21;

    float infrastructure_cost_factor = 22;
    float orbital_pos_r = 23;
    int32 max_population = 24;
    repeated planet_effect_t effects = 25;

    repeated nation_and_object_id_t settlement_ids = 26;
}

message location_object_t
{
    repeated nation_and_object_id_t bases = 1;
    uint64 planet_id = 2; // no planet if < 0
    // TODO: orbital position, if planet is nonzero
    // TODO: other kinds of things as well?
}

message system_location_t
{
    repeated location_object_t objects = 1;
    fleets_t units = 2;
}

enum star_class_t {
    invalid_star_class = 0;
    o = 1;
    b = 2;
    a = 3;
    f = 4;
    g = 5;
    k = 6;
    m = 7;
}

message star_t
{
    star_class_t star_class = 1;
    double temperature_k = 2;
    double solar_masses = 3;
    double solar_luminosities = 4;
    double solar_radii = 5;
}

message system_t
{
    string name = 1;
    int32 hex_id = 2;
    star_t star = 3;
    repeated system_location_t permanent_locations = 4;
    repeated system_location_t temporary_locations = 5;
    double world_pos_x = 6;
    double world_pos_y = 7;
    uint64 first_planet = 8;
    uint64 last_planet = 9;
}

message hex_t
{
    hex_coord_t coord = 1;
    int32 province_id = 2;
    uint64 first_system = 3;
    uint64 last_system = 4;
}

message province_t
{
    nation_and_object_id_t id = 1;
    repeated hex_coord_t hex_coords = 2;
}

message nation_t
{
    int32 id = 1;
    int32 home_planet = 2;
    nation_and_object_id_t capitol_settlement = 3;

    int32 money = 4;

    repeated unit_design_t unit_designs = 5;

    repeated province_t provinces = 6;
    repeated settlement_t settlements = 7; // may contain gaps (gaps have invald IDs)
    repeated fleet_t fleets = 8; // may contain gaps (gaps have invald IDs)
    int32 transports = 9;

    repeated int32 hexes_seen = 10; // these lists of IDs must be kept sorted
    repeated int32 systems_present_in = 11;
    repeated int32 systems_visited = 12;
    repeated int32 planets_surveyed = 13;
    repeated settlement_t settlements_seen = 14;
    repeated nation_and_object_id_t foreign_designs_seen = 15;
    repeated nation_and_object_id_t foreign_designs_glimpsed = 16;

    // techs are [1, 50]; partial values are research in progress
    float construction_tech = 17;
    float propulsion_tech = 18;
    float weapons_tech = 19;
    float shields_tech = 20;
    float stealth_tech = 21;
    float detection_tech = 22;
    float automation_tech = 23;

    // engineering traditions are [0, 100]
    int32 construction_tradition = 24;
    int32 propulsion_tradition = 25;
    int32 weapons_tradition = 26;
    int32 shields_tradition = 27;
    int32 stealth_tradition = 28;
    int32 detection_tradition = 29;

    bool defeated = 100;
}

message date_t
{
    int32 year = 1;
    int32 month = 2;
    int32 day = 3;
}

message game_state_t
{
    int32 map_width = 1;
    int32 map_height = 2;
    repeated hex_t hexes = 3;
    repeated system_t systems = 4;
    repeated planet_t planets = 5;
    repeated nation_t nations = 6;
    repeated uint32 alliances = 7; // packed bitfield
    int32 play_speed = 8; // 1-4 have fixed rates; 5 is as fast as it will go
    date_t date = 9;
}

message cost_t
{
   float money_cost = 1;
   float metal_cost = 2;
   float energy_cost = 3;
   float fuel_minerals_cost = 4;
   float fuel_cost = 5;
   float water_cost = 6;
   float food_cost = 7;
}

message day_update_t
{
    date_t date = 1;
    // TODO
}

message month_update_t
{
    date_t date = 1; // TODO
    // TODO
}

message year_update_t
{
    date_t date = 1; // TODO
    // TODO
}
