syntax = "proto3";

import "base_types.proto";

package pb_message.game_data;


message nation_and_object_id_t
{
    int32 nation_id = 1;
    int32 object_id = 2;
}

message game_start_params_t
{
    // TODO: scenario
    // TODO: options for development levels?

    float habitable_systems_per_hex_mean = 1; // Must be >= 0.1.
    float habitable_systems_per_hex_plus_minus = 2; // interpreted as 3 sigmas
    int32 systems_per_hex = 3; // total, not habitable
    int32 map_height = 4; // In hexes; must be an odd number >= 11.

    map<int32, int32> player_id_to_nation_id = 5; // size of this is the number of human players
}

message unit_design_t
{
    nation_and_object_id_t id = 1;
    int32 hull = 2;
    int32 armor = 3;
    int32 propulsion = 4;
    int32 weapons = 5;
    int32 shields = 6;
    int32 detection = 7;
    int32 stealth = 8;
    int32 automation = 9;
    int32 attack = 10;
    int32 defense = 11;
    int32 ground_attack = 12;
}

message unit_t
{
    nation_and_object_id_t id = 1;
    int32 health = 2; // <= design.defense
}

message fleet_position_t
{
    // always used
    double world_pos_x = 1;
    double world_pos_y = 2;

    // unused (system_id is a negative value) when between systems
    int32 system_id = 3;
    bool at_permanent_location = 4;
    int32 location_index = 5;
    int32 object_index = 6; // -1 if this fleet is not at a particular object
    bool is_garrison = 7; // only meaningful if object_index != -1, and the associated .planet_id != -1 too
};

message fleet_t
{
    nation_and_object_id_t id = 1; // -1 for both of these indicates this fleet is invalid
    pb_message.mission_t mission = 2;
    repeated unit_t units = 3;
    float fuel = 4;
    int32 rounds = 5;
    int32 missiles = 6;
    int32 fighters = 7;
    fleet_position_t position = 8;
}

message fleets_t
{
    map<int32, int32> fleet_ids = 1;
}

enum planet_type_t {
    invalid_planet_type = 0;
    rocky = 1;
    gas_giant = 2;              // U"gas giant"
    ice_giant = 3;              // U"ice giant"
}

enum atmosphere_type_t {
    invalid_atmosphere_type = 0;
    reduced_type_a = 1;
    oxidized_type_b = 2;
    carbon_rich_type_c = 3;
    high_temperature = 4;
    gas_giant_atmosphere = 5;
    ice_giant_atmosphere = 6;
}

enum planet_effect_target_t {
    invalid_planet_effect_target = 0;
    gravity = 1;
    axial_tilt = 2;
    day = 3;
    surface_temperature = 4;
    magnetosphere_strength = 5;
    atmopsheric_pressure = 6;
    o2_co2_suitability = 7;
    growth_factor = 8;
    water = 9;
    food = 10;
    energy = 11;
    metal = 12;
    fuel = 13;
    population = 14;
    infrastructure = 15;
    max_population = 16;
}

// FLAGS
enum planet_effect_mod_t {
    invalid_planet_effect_mod = 0;
    monthly = 1;   // Apply op monthly, rather than one time.
    cost = 2;      // Applies to the cost of the target property, not the property itself.
}

enum effect_op_t {
    invalid_effect_op = 0;
    add = 1;
    multiply = 2;
}

message planet_effect_t
{
    string name = 1;
    string description = 2;
    float amount = 3;
    int32 months_of_effect = 4;
    int32 months_remaining = 5;
    planet_effect_target_t target = 6;
    uint32 target_modifiers = 7;
    effect_op_t operation = 8;
}

// TODO: We should add a notion of a settlement, so that there can be more
// than one on a planet (one each from each neation present)
message planet_t
{
    int32 system_id = 1;
    planet_type_t planet_type = 2;
    double mass_kg = 3;
    double radius_km = 4;
    float orbit_au = 5;
    float orbital_period_y = 6; // in Earth years
    float gravity_g = 7; // in G's
    float axial_tilt_d = 8;
    float day_h = 9;
    float surface_temperature_k = 10;
    float magnetosphere_strength = 11; // Earth-scaled (1.0 is like Earth)
    float atmopsheric_pressure = 12; // In "atmospheres" (1.0 is like Earth)
    float o2_co2_suitability = 13; // only applies when atmosphere_type is oxidized_type_b; Earth-scaled
    float ocean_coverage = 14;
    float growth_factor = 15;
    atmosphere_type_t atmosphere_type = 16;
    int32 water = 17;
    int32 food = 18;
    int32 energy = 19;
    int32 metal = 20;
    int32 fuel = 21;

    // These two are floats because they grow over time; the effeective
    // property is the truncated integral value though.
    float population = 22;
    float infrastructure = 23;

    float orbital_pos_r = 24;
    int32 max_population = 25;
    int32 owner = 26; // TODO: Ownership of planets should go away.
    int32 original_owner = 27;
    // TODO: language, culture, religion
    // TODO: visual properties (incl. rings)
    nation_and_object_id_t garrison = 28;
    // TODO: ground-to-space defenses
    repeated planet_effect_t effects = 29;
}

message location_object_t
{
    repeated nation_and_object_id_t bases = 1;
    uint64 planet_id = 2; // no planet if < 0
    // TODO: orbital position, if planet is nonzero
    // TODO: other kinds of things as well?
}

message system_location_t
{
    repeated location_object_t objects = 1;
    fleets_t units = 2;
}

enum star_class_t {
    invalid_star_class = 0;
    o = 1;
    b = 2;
    a = 3;
    f = 4;
    g = 5;
    k = 6;
    m = 7;
}

message star_t
{
    star_class_t star_class = 1;
    double temperature_k = 2;
    double solar_masses = 3;
    double solar_luminosities = 4;
    double solar_radii = 5;
}

message system_t
{
    string name = 1;
    hex_coord_t coord = 2;
    star_t star = 3;
    repeated system_location_t permanent_locations = 4;
    repeated system_location_t temporary_locations = 5;
    double world_pos_x = 6;
    double world_pos_y = 7;
    uint64 first_planet = 8;
    uint64 last_planet = 9;
}

message hex_t
{
    hex_coord_t coord = 1;
    int32 province_id = 2;
    uint64 first_system = 3;
    uint64 last_system = 4;
}

message province_t
{
    nation_and_object_id_t id = 1;
    repeated hex_coord_t hex_coords = 2;
}

message nation_t
{
    int32 id = 1;
    repeated unit_design_t unit_designs = 2;
    repeated province_t provinces = 3;
    repeated fleet_t fleets = 4; // may contain gaps, in the form of invalid fleets
    repeated int32 hexes_seen = 5; // all these lists of IDs must be kept sorted
    repeated int32 systems_present_in = 6;
    repeated int32 systems_visited = 7;
    repeated int32 planets_present_on = 8;
    repeated int32 planets_surveyed = 9;
    repeated nation_and_object_id_t foreign_designs_seen = 10;
    repeated nation_and_object_id_t foreign_designs_glimpsed = 11;
    bool defeated = 12;
}

message game_state_t
{
    int32 map_width = 1;
    int32 map_height = 2;
    repeated hex_t hexes = 3;
    repeated system_t systems = 4;
    repeated planet_t planets = 5;
    repeated nation_t nations = 6;
    repeated uint32 alliances = 7; // packed bitfield
    int32 play_speed = 8; // 0=paused; 1-4 have fixed rates; 5 is as fast as it will go
}

// TODO: Need some kind of system for effects, and another one for
// predicates/triggers.  These should probably be in their own files.
// TODO message create_fleet
// TODO {
// TODO };
// TODO 
// TODO message merge_fleets
// TODO {
// TODO     int32 fleet_1 = 1;
// TODO     int32 fleet_2 = 2;
// TODO };
// TODO 
// TODO message disband_fleet
// TODO {
// TODO     int32 fleet = 1;
// TODO };
