set(lua_source_files
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lapi.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lauxlib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lbaselib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lcode.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lcorolib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lctype.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ldblib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ldebug.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ldo.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ldump.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lfunc.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lgc.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/linit.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/liolib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/llex.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lmathlib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lmem.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/loadlib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lobject.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lopcodes.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/loslib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lparser.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lstate.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lstring.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lstrlib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ltable.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ltablib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/ltm.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lundump.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lutf8lib.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lvm.c
    ${CMAKE_SOURCE_DIR}/unreal_project/Spaceport/Source/Spaceport/lua/lzio.c)
set_source_files_properties(${lua_source_files} PROPERTIES LANGUAGE CXX)
